### ISSUE TITLE
Autocomplete with colon doesnt work!

### ISSUE THREAD

**Issue by nodkrot** [P233/Emmet-Css-Snippets-for-Sublime-Text-2#11]
if i enter "pos" it shows proper suggestions. However, once I enter colon ":" like so "pos:" suggestions disappear. Any ideas?

I'm using Sublime Text 3 on Windows 8.1

**Comment by P233** [comment]
Sublime text doesn't support punctuation as snippet trigger. just ignore the `:` . It is only used for separating property name and property value
