### ISSUE TITLE
first-child [fc] snippet not working

### ISSUE THREAD

**Issue by ig-pep** [P233/Emmet-Css-Snippets-for-Sublime-Text-2#12]
Hi, I'm trying to use this with selectors e.g. 'div:first-child' but it doesn't seem to be working.

I've tried typing 'divfc' / 'div+fc' then pressing tab but with no result... Please let me know how I should be using it. Many thanks in advance.

**Comment by P233** [comment]
Hi @ig-pep. this package only contains vanilla sublime text snippets. You can type `fc` to trigger this snippet and the type the selector name, then press `TAB` to start typing styles
