### ISSUE TITLE
Missing ; for Sass completions

### ISSUE THREAD

**Issue by aprofromindia** [P233/Emmet-Css-Snippets-for-Sublime-Text-2#3]
For all scss auto-completions, I'm missing the ';' at the end.

e.g. -> fl:l -> float: left -> no ';' at the end.

I have uninstalled and re-installed your package

**Comment by aprofromindia** [comment]
closed for sass plugin install instead of scss

**Comment by P233** [comment]
Sorry about the inconvenience. I am working on a new syntax highlighting package for Sass to solve this problem, please give it a try. 

[Syntax Highlighting for Sass](https://github.com/P233/Syntax-highlighting-for-Sass)

**Comment by lmartins** [comment]
Im also having this issue, and im also using the mentioned new syntax highlighting for scss.
Any updates expected on this?

And thanks for one of the best packages i have on my Sublime install ;-)

**Comment by P233** [comment]
@lmartins Thanks :smile:  It should be work fine now. If the problem still exists, let me know please.

**Comment by lmartins** [comment]
Yes, thank you. :-)
