### ISSUE TITLE
[Survey] Remove vendor prefix?

### ISSUE THREAD

**Issue by P233** [P233/Emmet-Css-Snippets-for-Sublime-Text-2#5]
I am thinking of removing all vendor-prefix, and then start using https://github.com/ai/autoprefixer

What do you think?

**Comment by lunelson** [comment]
I just came over here to post this exact question. I'd like to see a user prefs option to disable them, if possible. I've moved to autoprefixer.

**Comment by P233** [comment]
@lunelson Thank you for your reply. I am trying to find a simple way to disable/enable snippets for Sublime Text (I know nothing about Python). If I can't find, I am afraid removing all prefix is the only option :(

**Comment by lunelson** [comment]
I know nothing about Python either, but probably you could find out in the Sublime forums whether this is at all possible. Otherwise, I'd suggest perhaps making a new version of the package without the prefixes and then maintaining both? It might be a bit confusing but I know I'd appreciate having the option.

**Comment by P233** [comment]
@lunelson It now has two snippet versions: one with vendor prefixes and another one without. you can add `has-Prefix` or `no-Prefix` to the `ignored_packages` list of sublime settings file. :)

**Comment by lunelson** [comment]
Thanks, it's really nice to see this feature—but didn't this collection of snippets use to include SCSS shortcuts too? For `@include` and `@extend`? Or what do you use now for that? I use your syntax btw.

**Comment by P233** [comment]
@lunelson these snippets has been moved to the Syntax Highlighting package as built-in completions. please see https://github.com/P233/Syntax-highlighting-for-Sass/blob/master/Completions/SHS-At-Rule/At-rule.sublime-completions and https://github.com/P233/Syntax-highlighting-for-Sass#built-in-completion-packages

Thank you for using these packages :)

**Comment by lunelson** [comment]
@P233 Thank you for making them! I spend a lot of time in SCSS and your syntax highlighter is by far the best. Thanks for the tips re the completions, I get it now ;)

**Comment by P233** [comment]
cheers @lunelson
